#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


export DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-config.settings.local}
echo "START: DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
python manage.py migrate
exec uvicorn config.asgi:application \
	--host 0.0.0.0 \
	--reload \
	--reload-include '*.html' \
	--reload-exclude '.ipython/**'
