#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
export DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-config.settings.local}
exec uvicorn config.asgi:application \
	--host 0.0.0.0 \
	--reload \
	--reload-include '*.html' \
	--reload-exclude '.ipython/**'
