# Generated by Django 5.1.11 on 2025-11-12 13:34

import hr_payroll.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50)),
                ('contract_name', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=hr_payroll.employees.models.employee_photo_upload_to)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
                ('office', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health_care', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=hr_payroll.employees.models.employee_document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
                ('position_type', models.CharField(blank=True, max_length=50)),
                ('employment_type', models.CharField(blank=True, choices=[('fulltime', 'Fulltime'), ('parttime', 'Part-time'), ('contract', 'Contract')], max_length=20)),
            ],
            options={
                'ordering': ['effective_date', 'pk'],
            },
        ),
    ]
