# Generated by Django 5.1.11 on 2025-09-25 10:01

import hr_payroll.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=hr_payroll.employees.models.employee_upload_to),
        ),
    ]
