# Generated by Django 5.1.11 on 2025-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="fingerprint_token",
            field=models.CharField(
                max_length=128,
                unique=True,
                blank=True,
                null=True,
                help_text=(
                    "Opaque identifier for fingerprint/device enrollment; can be any string "
                    "provided by sensor/mobile device."
                ),
            ),
        ),
    ]
