# Generated by Django 5.1.11 on 2025-10-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_department_created_at_and_more'),
        ('employees', '0004_position_and_hr_fields'),
    ]

    operations = [
    ]
