# Generated by Django 5.1.11 on 2025-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_add_fingerprint_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fingerprint_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
