# Generated by Django 5.1.11 on 2026-01-02 13:32

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_emergencycontact_employeeaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
