# Generated by Django 5.1.11 on 2026-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_country_field_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_shift',
            field=models.CharField(blank=True, help_text='Name of the shift from Policy', max_length=100),
        ),
    ]
