# Generated by Django 5.1.11 on 2025-10-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_national_id_partial_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniq_employee_national_id_nonblank',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
