# Generated by Django 5.1.11 on 2026-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_current_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='notice_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated from terminationPolicy based on status', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]
