# Generated by Django 5.1.11 on 2025-10-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_date_of_birth_employee_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_birth',
            new_name='last_working_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='health_care',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='personal_tax_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='social_insurance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
