# Generated by Django 5.1.11 on 2025-11-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
    ]
