# Generated by Django 5.1.11 on 2025-11-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_remove_department_manager'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='org.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_care',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
