# Generated by Copilot
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("shift_name", models.CharField(blank=True, default="", max_length=100)),
                ("shift_start", models.TimeField(blank=True, null=True)),
                ("shift_end", models.TimeField(blank=True, null=True)),
                ("clock_in", models.TimeField(blank=True, null=True)),
                ("clock_out", models.TimeField(blank=True, null=True)),
                ("clock_in_location", models.CharField(blank=True, default="", max_length=100)),
                ("clock_out_location", models.CharField(blank=True, default="", max_length=100)),
                ("paid_minutes", models.PositiveIntegerField(default=0)),
                ("work_schedule_minutes", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("present", "Present"), ("absent", "Absent"), ("partial", "Partial")], default="pending", max_length=16)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="employees.employee")),
            ],
            options={
                "ordering": ["-date", "-id"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="OfficeNetworkRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cidr", models.CharField(help_text="CIDR, e.g. 192.168.0.0/24", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttendancePunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("punch_type", models.CharField(choices=[("check_in", "Check in"), ("check_out", "Check out"), ("break_start", "Break start"), ("break_end", "Break end")], max_length=20)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attendance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="punches", to="attendance.attendancerecord")),
            ],
            options={
                "ordering": ["timestamp", "id"],
            },
        ),
    ]
