# Generated by Django 5.1.11 on 2025-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
