# Generated by Django 5.1.11 on 2025-11-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_overtime_seconds'),
    ]

    # No-op migration to mark 0003 as applied after reverting to UUID PK.
    operations = []
