# Generated by Django 5.1.11 on 2025-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
