# Generated by Django 5.1.11 on 2025-11-22 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_employee_fingerprint_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Policy Name (e.g., Senior Annual)', max_length=100)),
                ('description', models.TextField(help_text='Description input field')),
                ('assign_schedule', models.CharField(choices=[('On Joining', 'On Joining'), ('Manual', 'Manual')], default='On Joining', max_length=20)),
                ('accrual_frequency', models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], default='Yearly', max_length=20)),
                ('entitlement', models.DecimalField(decimal_places=2, help_text='Entitlement (Days per year)', max_digits=5)),
                ('max_carry_over', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum Carry Over', max_digits=5)),
                ('carry_over_expire_month', models.PositiveIntegerField(help_text='Carry Over Expiration (Month)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('carry_over_expire_day', models.PositiveIntegerField(help_text='Carry Over Expiration (Day)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('allow_hourly', models.BooleanField(default=False, help_text='Duration Allowed: Hourly toggle')),
                ('eligibility_gender', models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], default='All', help_text='Eligibility', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle switch')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Engagement, Annual, Sick', max_length=100, unique=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Toggle: Paid / Unpaid')),
                ('unit', models.CharField(choices=[('Days', 'Days'), ('Hours', 'Hours')], default='Days', help_text='Selection: Days or Hours', max_length=10)),
                ('color_code', models.CharField(help_text='Hex Code (e.g., #00FF00)', max_length=7)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday Name (e.g., Eid Mubarak)', max_length=100)),
                ('start_date', models.DateField(help_text='From date')),
                ('end_date', models.DateField(help_text='To date')),
                ('year', models.IntegerField(help_text='Index for fast calendar filtering')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='From / Select Date')),
                ('end_date', models.DateField(help_text='To / Select Date')),
                ('start_time', models.TimeField(blank=True, help_text='Used if allow_hourly is True', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Used if allow_hourly is True', null=True)),
                ('duration', models.DecimalField(decimal_places=2, help_text='Total (e.g., 3 Days)', max_digits=5)),
                ('notes', models.TextField(blank=True, default='', help_text='Note input field')),
                ('attachment', models.FileField(blank=True, help_text='Upload attachment', null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Status Badge', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='If status is Rejected, reason why')),
                ('assigned_approver', models.ForeignKey(blank=True, help_text='Assign To search field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to='employees.employee')),
                ('employee', models.ForeignKey(help_text='Employee Name', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('policy', models.ForeignKey(help_text='Time Off Type dropdown', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leaves.leavepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Taken', 'Taken'), ('Accrual', 'Accrual'), ('Manual Adjustment', 'Manual Adjustment')], help_text='Event column', max_length=50)),
                ('date', models.DateField(help_text='Date column')),
                ('change_amount', models.DecimalField(decimal_places=2, help_text='Change (Days) (+/- values)', max_digits=6)),
                ('changed_by', models.ForeignKey(help_text='Changed By column', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The employee involved', on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='employees.employee')),
                ('policy', models.ForeignKey(help_text='Type column', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leaves.leavepolicy')),
                ('related_request', models.ForeignKey(blank=True, help_text='Links to the specific request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='leaves.leaverequest')),
            ],
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leaves.leavetype'),
        ),
        migrations.CreateModel(
            name='EmployeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitled_days', models.DecimalField(decimal_places=2, help_text='Total allowance', max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0.0, help_text='Used days', max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0.0, help_text='Days locked in Pending requests', max_digits=6)),
                ('carry_forward_days', models.DecimalField(decimal_places=2, default=0.0, help_text='Days brought over from last year', max_digits=6)),
                ('employee', models.ForeignKey(help_text='The user who owns this balance', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('policy', models.ForeignKey(help_text='The rules governing this balance', on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavepolicy')),
            ],
            options={
                'unique_together': {('employee', 'policy')},
            },
        ),
    ]
