# Generated by Django 5.1.11 on 2025-11-12 13:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('recurring', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('one_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('offset', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_compensation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('actual_work_seconds', models.IntegerField(default=0)),
                ('overtime_seconds', models.IntegerField(default=0)),
                ('deficit_seconds', models.IntegerField(default=0)),
                ('carry_over_overtime_seconds', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cycle__period_end', 'employee_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('base', 'Base'), ('recurring', 'Recurring'), ('one_off', 'One-off'), ('offset', 'Offset')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('swift_bic', models.CharField(blank=True, max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='employees.employee')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compensation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.employee')),
            ],
            options={
                'ordering': ['employee_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('cutoff_date', models.DateField()),
                ('review_cutoff_date', models.DateField(blank=True, null=True)),
                ('review_cutoff_enabled', models.BooleanField(default=False)),
                ('eligibility_criteria', models.CharField(choices=[('all', 'All Employees'), ('list', 'Selected Employees')], default='all', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_employees', models.ManyToManyField(blank=True, related_name='eligible_cycles', to='employees.employee')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
    ]
