# Generated by Django 5.1.11 on 2025-11-22 10:57

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_employee_fingerprint_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bank name (e.g., "Chase Bank")', max_length=200, unique=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=50)),
                ('code', models.CharField(blank=True, help_text='Local bank code or routing number', max_length=50)),
            ],
            options={
                'verbose_name': 'Bank Master',
                'verbose_name_plural': 'Bank Masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollGeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', help_text='ISO Currency Code', max_length=3)),
                ('proration_policy', models.CharField(choices=[('fixed_day', 'Fixed Day'), ('actual_days', 'Actual Days')], default='fixed_day', help_text='Proration policy for partial months', max_length=20)),
                ('working_days_basis', models.IntegerField(default=20, help_text='Standard working days per month')),
            ],
            options={
                'verbose_name': 'Payroll General Setting',
                'verbose_name_plural': 'Payroll General Settings',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Component name (e.g., "Basic Salary", "Transport Allowance")', max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], default='earning', help_text='Type of component', max_length=20)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this component is subject to tax')),
                ('is_recurring', models.BooleanField(default=True, help_text='False for one-off payments like bonuses')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, help_text='Specific branch location', max_length=200)),
                ('account_holder', models.CharField(help_text='Name on the account', max_length=200)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=100)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='employees.employee')),
                ('bank', models.ForeignKey(help_text='Bank where account is held', on_delete=django.db.models.deletion.PROTECT, to='payroll.bankmaster')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Dependent's full name", max_length=200)),
                ('relationship', models.CharField(blank=True, help_text='Relationship (e.g., "Spouse", "Child")', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Dependent',
                'verbose_name_plural': 'Dependents',
                'ordering': ['employee_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base monthly salary', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Salary Structure',
                'verbose_name_plural': 'Employee Salary Structures',
            },
        ),
        migrations.CreateModel(
            name='PayCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cycle name (e.g., "January 2025")', max_length=150)),
                ('start_date', models.DateField(help_text='Cycle start date')),
                ('end_date', models.DateField(help_text='Cycle end date')),
                ('cutoff_date', models.DateField(help_text='Cut-off date for processing')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('closed', 'Closed')], default='draft', help_text='Cycle status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_in_charge', models.ForeignKey(blank=True, help_text='Manager responsible for this cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cycles', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Pay Cycle',
                'verbose_name_plural': 'Pay Cycles',
                'ordering': ['-end_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base salary snapshot', max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deductions', max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net pay (earnings - deductions)', max_digits=12)),
                ('total_work_duration', models.DurationField(default=datetime.timedelta(0), help_text='Total work time')),
                ('total_overtime_duration', models.DurationField(default=datetime.timedelta(0), help_text='Total overtime')),
                ('total_deficit_duration', models.DurationField(default=datetime.timedelta(0), help_text='Total deficit time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid')], default='draft', help_text='Slip status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='payroll.paycycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Payroll Slip',
                'verbose_name_plural': 'Payroll Slips',
                'ordering': ['-cycle__end_date', 'employee_id', '-created_at'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display label (e.g., "Overtime (10 hours)")', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Line item amount', max_digits=12)),
                ('category', models.CharField(choices=[('recurring', 'Recurring'), ('one_off', 'One-off'), ('overtime', 'Overtime'), ('tax', 'Tax')], help_text='Category for grouping', max_length=20)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.payrollslip')),
                ('component', models.ForeignKey(blank=True, help_text='Reference to salary component', null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.salarycomponent')),
            ],
            options={
                'verbose_name': 'Payslip Line Item',
                'verbose_name_plural': 'Payslip Line Items',
                'ordering': ['slip', 'category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this component', max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarycomponent')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.employeesalarystructure')),
            ],
            options={
                'verbose_name': 'Salary Structure Item',
                'verbose_name_plural': 'Salary Structure Items',
                'unique_together': {('structure', 'component')},
            },
        ),
        migrations.AddField(
            model_name='employeesalarystructure',
            name='components',
            field=models.ManyToManyField(related_name='structures', through='payroll.SalaryStructureItem', to='payroll.salarycomponent'),
        ),
    ]
