# Generated by Django 5.1.11 on 2025-11-12 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcycle',
            name='person_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollcycle'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='compensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.compensation'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('cycle', 'employee')},
        ),
    ]
