# Generated by Django 5.1.11 on 2025-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslipdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
