# Generated by Django 5.1.11 on 2025-12-23 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payslipdocument_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Code',
                'verbose_name_plural': 'Tax Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='payroll.paycycle')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Flat rate as fraction (e.g., 0.1000 for 10%)', max_digits=7, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='payroll.taxcode')),
            ],
            options={
                'verbose_name': 'Tax Code Version',
                'verbose_name_plural': 'Tax Code Versions',
                'ordering': ['tax_code_id', '-effective_from', '-created_at'],
                'unique_together': {('tax_code', 'effective_from')},
            },
        ),
    ]
