# Generated by Django 5.1.11 on 2026-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Category from announcementPolicy (e.g., Urgent, General)', max_length=50),
        ),
    ]
