# Generated by Django 5.1.11 on 2025-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('audit', '0002_auditlog_structured_fields'),
    ]

    operations = [
        # Backfill existing NULLs to empty strings before making fields non-nullable
        migrations.RunSQL(
            sql="UPDATE audit_auditlog SET ip_address = '' WHERE ip_address IS NULL;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="UPDATE audit_auditlog SET model_name = '' WHERE model_name IS NULL;",
            reverse_sql="",
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
