# Generated by Django 5.1.11 on 2025-11-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_health_care_userprofile_marital_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='uniq_userprofile_national_id_nonblank',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='national_id',
            new_name='time_zone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
