# Generated by Django 5.1.11 on 2025-11-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_uniq_userprofile_national_id_nonblank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='health_care',
        ),
    ]
